import { useState } from 'react'
import './App.css'

const INITIAL_FORM_STATE = {
  // Section 1
  network: '',
  deductibleTotal: '',
  deductibleMet: '',
  oopMaxTotal: '',
  oopMet: '',
  deductibleOopStructure: '',

  // Section 2
  currentLoc: '',
  verifiedLoc: '',

  // Section 3
  deductibleApplies: '',
  coinsurancePercent: '',
  locRulesConfirmed: false,

  // Section 4
  hasPriorLoc: '',
  priorFinancialsReviewed: false,
  hasCurrentBalance: '',
  balanceAmount: '',
  balanceType: '',

  // Section 5
  hasScholarship: '',
  scholarshipAmount: '',
  scholarshipAppliesTo: [],
  countsTowardOopConfirmed: false,

  // Section 6
  deductibleOopReviewed: false,
  networkConfirmed: false,
  locRulesEntered: false,
  priorLocCreditsReviewed: false,
  balanceReviewed: false,
}

function generateExplanation(data) {
  const lines = []

  lines.push('CLIENT INSURANCE SUMMARY')
  lines.push('═'.repeat(50))

  // Network
  if (data.network) {
    lines.push(`Network: ${data.network}`)
  }

  // Deductible
  const dedTotal = data.deductibleTotal ? `$${data.deductibleTotal}` : 'N/A'
  const dedMet = data.deductibleMet ? `$${data.deductibleMet}` : 'N/A'
  if (data.deductibleTotal || data.deductibleMet) {
    const dedRemaining =
      data.deductibleTotal && data.deductibleMet
        ? ` ($${(parseFloat(data.deductibleTotal) - parseFloat(data.deductibleMet)).toFixed(2)} remaining)`
        : ''
    lines.push(`Deductible: ${dedMet} met of ${dedTotal}${dedRemaining}`)
  }

  // OOP Max
  const oopTotal = data.oopMaxTotal ? `$${data.oopMaxTotal}` : 'N/A'
  const oopMet = data.oopMet ? `$${data.oopMet}` : 'N/A'
  if (data.oopMaxTotal || data.oopMet) {
    const oopRemaining =
      data.oopMaxTotal && data.oopMet
        ? ` ($${(parseFloat(data.oopMaxTotal) - parseFloat(data.oopMet)).toFixed(2)} remaining)`
        : ''
    lines.push(`Out-of-Pocket Max: ${oopMet} met of ${oopTotal}${oopRemaining}`)
  }

  if (data.deductibleOopStructure) {
    lines.push(`Deductible/OOP Structure: ${data.deductibleOopStructure}`)
  }

  lines.push('')

  // LOC
  if (data.verifiedLoc) {
    lines.push(`Verified Level of Care: ${data.verifiedLoc}`)
  }
  if (data.currentLoc && data.currentLoc !== data.verifiedLoc) {
    lines.push(`Current Level of Care: ${data.currentLoc}`)
    lines.push('⚠ Rules applied are for Verified LOC only.')
  }

  lines.push('')

  // LOC Rules
  if (data.deductibleApplies) {
    lines.push(
      `Deductible Applies for ${data.verifiedLoc || 'Verified LOC'}: ${data.deductibleApplies}`
    )
  }
  if (data.coinsurancePercent) {
    lines.push(`Coinsurance Rate: ${data.coinsurancePercent}%`)
  }

  lines.push('')

  // Financial State
  if (data.hasPriorLoc === 'Yes') {
    lines.push('Prior LOC: Yes')
    if (data.priorFinancialsReviewed) {
      lines.push('  Prior financials have been reviewed.')
    }
  }

  if (data.hasCurrentBalance === 'Yes') {
    const balAmt = data.balanceAmount ? `$${data.balanceAmount}` : 'amount not specified'
    const balType = data.balanceType ? ` (${data.balanceType})` : ''
    lines.push(`Current Balance: ${balAmt}${balType}`)
  }

  lines.push('')

  // Financial Assistance
  if (data.hasScholarship === 'Yes') {
    const schAmt = data.scholarshipAmount ? `$${data.scholarshipAmount}` : 'amount not specified'
    lines.push(`Scholarship/Hardship Assistance: ${schAmt}`)
    if (data.scholarshipAppliesTo.length > 0) {
      lines.push(`  Applies to: ${data.scholarshipAppliesTo.join(', ')}`)
    }
    if (data.countsTowardOopConfirmed) {
      lines.push('  Confirmed to count toward OOP.')
    }
  }

  lines.push('')
  lines.push('─'.repeat(50))
  lines.push('Generated by Insurance Snapshot System')

  return lines.join('\n')
}

function RadioGroup({ name, options, value, onChange }) {
  return (
    <div className="radio-group">
      {options.map((opt) => (
        <label key={opt} className="radio-label">
          <input
            type="radio"
            name={name}
            value={opt}
            checked={value === opt}
            onChange={() => onChange(opt)}
          />
          {opt}
        </label>
      ))}
    </div>
  )
}

function CurrencyInput({ id, value, onChange, placeholder = '0.00' }) {
  return (
    <div className="currency-input-wrapper">
      <span className="currency-symbol">$</span>
      <input
        id={id}
        type="number"
        min="0"
        step="0.01"
        className="currency-input"
        value={value}
        onChange={(e) => onChange(e.target.value)}
        placeholder={placeholder}
      />
    </div>
  )
}

export default function App() {
  const [form, setForm] = useState(INITIAL_FORM_STATE)
  const [submitted, setSubmitted] = useState(false)
  const [explanation, setExplanation] = useState('')

  const set = (field) => (value) => setForm((prev) => ({ ...prev, [field]: value }))
  const setCheck = (field) => (e) => setForm((prev) => ({ ...prev, [field]: e.target.checked }))

  const toggleAppliesTo = (item) => {
    setForm((prev) => {
      const current = prev.scholarshipAppliesTo
      return {
        ...prev,
        scholarshipAppliesTo: current.includes(item)
          ? current.filter((x) => x !== item)
          : [...current, item],
      }
    })
  }

  const handleSubmit = (e) => {
    e.preventDefault()
    const text = generateExplanation(form)
    setExplanation(text)
    setSubmitted(true)
    window.scrollTo({ top: 0, behavior: 'smooth' })
  }

  const handleReset = () => {
    setForm(INITIAL_FORM_STATE)
    setSubmitted(false)
    setExplanation('')
  }

  const locsDifferent =
    form.currentLoc && form.verifiedLoc && form.currentLoc !== form.verifiedLoc

  return (
    <div className="app">
      <header className="app-header">
        <h1>INSURANCE SNAPSHOT</h1>
      </header>

      {submitted ? (
        <div className="explanation-card">
          <h2>Client Explanation</h2>
          <pre className="explanation-text">{explanation}</pre>
          <button className="btn-secondary" onClick={handleReset}>
            ← Start New Snapshot
          </button>
        </div>
      ) : (
        <form className="snapshot-form" onSubmit={handleSubmit}>
          {/* SECTION 1 */}
          <section className="form-section">
            <h2 className="section-title">Section 1 — Plan Basics</h2>

            <div className="field-group">
              <label className="field-label">Network</label>
              <RadioGroup
                name="network"
                options={['INN', 'OON', 'Both', 'Unknown']}
                value={form.network}
                onChange={set('network')}
              />
            </div>

            <div className="field-row">
              <div className="field-group">
                <label className="field-label" htmlFor="deductibleTotal">
                  Deductible Total
                </label>
                <CurrencyInput
                  id="deductibleTotal"
                  value={form.deductibleTotal}
                  onChange={set('deductibleTotal')}
                />
              </div>
              <div className="field-group">
                <label className="field-label" htmlFor="deductibleMet">
                  Deductible Met
                </label>
                <CurrencyInput
                  id="deductibleMet"
                  value={form.deductibleMet}
                  onChange={set('deductibleMet')}
                />
              </div>
            </div>

            <div className="field-row">
              <div className="field-group">
                <label className="field-label" htmlFor="oopMaxTotal">
                  OOP Max Total
                </label>
                <CurrencyInput
                  id="oopMaxTotal"
                  value={form.oopMaxTotal}
                  onChange={set('oopMaxTotal')}
                />
              </div>
              <div className="field-group">
                <label className="field-label" htmlFor="oopMet">
                  OOP Met
                </label>
                <CurrencyInput id="oopMet" value={form.oopMet} onChange={set('oopMet')} />
              </div>
            </div>

            <div className="field-group">
              <label className="field-label">Deductible / OOP Structure</label>
              <RadioGroup
                name="deductibleOopStructure"
                options={['Combined', 'Separate', 'Unsure']}
                value={form.deductibleOopStructure}
                onChange={set('deductibleOopStructure')}
              />
            </div>
          </section>

          {/* SECTION 2 */}
          <section className="form-section">
            <h2 className="section-title">Section 2 — Level of Care</h2>

            <div className="field-group">
              <label className="field-label">Current LOC (where client is now)</label>
              <RadioGroup
                name="currentLoc"
                options={['None', 'Detox', 'Resi', 'PHP', 'IOP', 'OP']}
                value={form.currentLoc}
                onChange={set('currentLoc')}
              />
            </div>

            <div className="field-group">
              <label className="field-label">Verified LOC (what this VOB is for)</label>
              <RadioGroup
                name="verifiedLoc"
                options={['Detox', 'Resi', 'PHP', 'IOP', 'OP']}
                value={form.verifiedLoc}
                onChange={set('verifiedLoc')}
              />
            </div>

            {locsDifferent && (
              <div className="warning-banner">
                ⚠ If different, system will apply rules for <strong>VERIFIED LOC</strong> only
              </div>
            )}
          </section>

          {/* SECTION 3 */}
          <section className="form-section">
            <h2 className="section-title">Section 3 — LOC Rule (For Verified LOC)</h2>

            <div className="field-group">
              <label className="field-label">Does Deductible Apply?</label>
              <RadioGroup
                name="deductibleApplies"
                options={['Yes', 'No', 'Unsure']}
                value={form.deductibleApplies}
                onChange={set('deductibleApplies')}
              />
            </div>

            <div className="field-group">
              <label className="field-label" htmlFor="coinsurancePercent">
                Coinsurance % (for this LOC)
              </label>
              <div className="percent-input-wrapper">
                <input
                  id="coinsurancePercent"
                  type="number"
                  min="0"
                  max="100"
                  step="1"
                  className="percent-input"
                  value={form.coinsurancePercent}
                  onChange={(e) => set('coinsurancePercent')(e.target.value)}
                  placeholder="0"
                />
                <span className="percent-symbol">%</span>
              </div>
            </div>

            <label className="checkbox-label">
              <input
                type="checkbox"
                checked={form.locRulesConfirmed}
                onChange={setCheck('locRulesConfirmed')}
              />
              LOC rules confirmed from insurance
            </label>
          </section>

          {/* SECTION 4 */}
          <section className="form-section">
            <h2 className="section-title">Section 4 — Current Financial State</h2>

            <div className="field-group">
              <label className="field-label">Has Prior LOC?</label>
              <RadioGroup
                name="hasPriorLoc"
                options={['Yes', 'No']}
                value={form.hasPriorLoc}
                onChange={set('hasPriorLoc')}
              />
            </div>

            {form.hasPriorLoc === 'Yes' && (
              <div className="conditional-block">
                <label className="checkbox-label">
                  <input
                    type="checkbox"
                    checked={form.priorFinancialsReviewed}
                    onChange={setCheck('priorFinancialsReviewed')}
                  />
                  Prior financials reviewed
                </label>
              </div>
            )}

            <div className="field-group">
              <label className="field-label">Current Balance?</label>
              <RadioGroup
                name="hasCurrentBalance"
                options={['Yes', 'No']}
                value={form.hasCurrentBalance}
                onChange={set('hasCurrentBalance')}
              />
            </div>

            {form.hasCurrentBalance === 'Yes' && (
              <div className="conditional-block">
                <div className="field-group">
                  <label className="field-label" htmlFor="balanceAmount">
                    Balance Amount
                  </label>
                  <CurrencyInput
                    id="balanceAmount"
                    value={form.balanceAmount}
                    onChange={set('balanceAmount')}
                  />
                </div>

                <div className="field-group">
                  <label className="field-label">Balance Type</label>
                  <RadioGroup
                    name="balanceType"
                    options={['Deductible', 'Coinsurance', 'Copay', 'Prior LOC', 'NSF', 'Other']}
                    value={form.balanceType}
                    onChange={set('balanceType')}
                  />
                </div>
              </div>
            )}
          </section>

          {/* SECTION 5 */}
          <section className="form-section">
            <h2 className="section-title">Section 5 — Financial Assistance</h2>

            <div className="field-group">
              <label className="field-label">Any Scholarship / Hardship?</label>
              <RadioGroup
                name="hasScholarship"
                options={['Yes', 'No']}
                value={form.hasScholarship}
                onChange={set('hasScholarship')}
              />
            </div>

            {form.hasScholarship === 'Yes' && (
              <div className="conditional-block">
                <div className="field-group">
                  <label className="field-label" htmlFor="scholarshipAmount">
                    Amount
                  </label>
                  <CurrencyInput
                    id="scholarshipAmount"
                    value={form.scholarshipAmount}
                    onChange={set('scholarshipAmount')}
                  />
                </div>

                <div className="field-group">
                  <label className="field-label">Applies To</label>
                  <div className="checkbox-group">
                    {['Deductible', 'OOP', 'Balance', 'Unsure'].map((item) => (
                      <label key={item} className="checkbox-label">
                        <input
                          type="checkbox"
                          checked={form.scholarshipAppliesTo.includes(item)}
                          onChange={() => toggleAppliesTo(item)}
                        />
                        {item}
                      </label>
                    ))}
                  </div>
                </div>

                <label className="checkbox-label">
                  <input
                    type="checkbox"
                    checked={form.countsTowardOopConfirmed}
                    onChange={setCheck('countsTowardOopConfirmed')}
                  />
                  Counts toward OOP confirmed
                </label>
              </div>
            )}
          </section>

          {/* SECTION 6 */}
          <section className="form-section">
            <h2 className="section-title">Section 6 — Final Check</h2>

            <div className="checklist">
              {[
                ['deductibleOopReviewed', 'Deductible/OOP reviewed'],
                ['networkConfirmed', 'Network confirmed'],
                ['locRulesEntered', 'LOC rules entered'],
                ['priorLocCreditsReviewed', 'Prior LOC + credits reviewed'],
                ['balanceReviewed', 'Balance reviewed'],
              ].map(([field, label]) => (
                <label key={field} className="checkbox-label checklist-item">
                  <input
                    type="checkbox"
                    checked={form[field]}
                    onChange={setCheck(field)}
                  />
                  {label}
                </label>
              ))}
            </div>
          </section>

          {/* SUBMIT */}
          <div className="submit-row">
            <button type="submit" className="btn-submit">
              SUBMIT → SYSTEM GENERATES CLIENT EXPLANATION
            </button>
          </div>
        </form>
      )}
    </div>
  )
}
